# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-spacelift-worker-pool
  description: This component provisions the `WorkerPool` part of the [Kubernetes Operator](https://docs.spacelift.io/concepts/worker-pools/kubernetes-workers#kubernetes-workers) for [Spacelift Worker Pools](https://docs.spacelift.io/concepts/worker-pools#kubernetes) into an EKS cluster
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component

